### ISSUE TITLE
Display a more helpful error message

### ISSUE THREAD

**Issue by iaindillingham** [iaindillingham/cohort-joiner#66]
If a glob pattern is passed as the value of the `--rhs` argument, then the error message is unhelpful. For example:

```
2022-08-23T09:40:12.883317084Z Exception at 2022-08-23 09:40:12 UTC
2022-08-23T09:40:12.883355084Z Traceback (most recent call last):
2022-08-23T09:40:12.883358619Z   File "analysis/cohort_joiner.py", line 105, in <module>
2022-08-23T09:40:12.883362701Z     main()
2022-08-23T09:40:12.883364899Z   File "analysis/cohort_joiner.py", line 95, in main
2022-08-23T09:40:12.883367051Z     rhs_dataframe = read_dataframe(rhs_path)
2022-08-23T09:40:12.883369165Z   File "analysis/cohort_joiner.py", line 12, in read_dataframe
2022-08-23T09:40:12.883371345Z     return pandas.read_csv(path)
2022-08-23T09:40:12.883373577Z   File "/opt/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
2022-08-23T09:40:12.883375825Z     return _read(filepath_or_buffer, kwds)
2022-08-23T09:40:12.883377917Z   File "/opt/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
2022-08-23T09:40:12.883380110Z     parser = TextFileReader(fp_or_buf, **kwds)
2022-08-23T09:40:12.883382332Z   File "/opt/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
2022-08-23T09:40:12.883384598Z     self._make_engine(self.engine)
2022-08-23T09:40:12.883386773Z   File "/opt/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
2022-08-23T09:40:12.883388976Z     self._engine = CParserWrapper(self.f, **self.options)
2022-08-23T09:40:12.883461709Z   File "/opt/venv/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
2022-08-23T09:40:12.883464423Z     self._reader = parsers.TextReader(src, **kwds)
2022-08-23T09:40:12.883466657Z   File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
2022-08-23T09:40:12.883469007Z   File "pandas/_libs/parsers.pyx", line 673, in pandas._libs.parsers.TextReader._setup_parser_source
2022-08-23T09:40:12.883471373Z FileNotFoundError: [Errno 2] File /workspace/output/input_ethnicity*.csv does not exist: '/workspace/output/input_ethnicity*.csv'


job_id: jyepaqyd5r4leeyc
job_request_id: af98f53586
commit: da032073105a29470dc969a90e8e637d58d634e8
docker_image_id: sha256:969e4c121558246102f239e628c3c12dfcda2362298f8508bd54de08920c1ca9
exit_code: 1
created_at: 1661247600
completed_at: 1661247614

outputs:
  (no outputs)
```

Could cohort-joiner display a more helpful error message?

**Comment by iaindillingham** [comment]
I think that we should probably test whether `rhs_path` is a glob. If it is, then I think we should raise an `argparse.ArgumentError` with a message, such as:

```
RHS_FILE should be a path to a dataframe, not a glob pattern
```

---

Not required, but we could also test whether:

* the path points to a file
* the file exists

And raise an `argparse.ArgumentError` with an appropriate message.
